services:
  - docker

script:
  - docker build -t chris13524/privatepm-client:latest client
  - docker build -t chris13524/privatepm-server:latest server

deploy:
  provider: script
  script: bash travis_dockerpush.sh
  on:
    branch: master
  skip_cleanup: true

env:
  global:
    - DOCKER_USERNAME=chris13524
