version: "3"
services:

  client:
    restart: always
    build:
      context: client
    environment:
      - API=//api.$DOMAIN

  server:
    restart: always
    build:
      context: server
    environment:
      - S3_ENDPOINT=$S3_ENDPOINT
      - S3_KEY_ID=$S3_KEY_ID
      - S3_KEY_SECRET=$S3_KEY_SECRET
      - S3_BUCKET=$S3_BUCKET
      - S3_PREFIX=$S3_PREFIX
    volumes:
      - ./server/database.sqlite3:/app/database.sqlite3

  exposer:
    restart: always
    image: valian/docker-nginx-auto-ssl
    environment:
      - ALLOWED_DOMAINS=$DOMAIN
      - SITES=$DOMAIN=client:80;api.$DOMAIN=server:80
    volumes:
      - ${DATA_DIR}/exposer/:/etc/resty-auto-ssl/
    ports:
      - "80:80"
      - "443:443"
