version: "3"
services:

  client:
    restart: always
    image: chris13524/privatepm-client:latest
    environment:
      - API=//api.$DOMAIN

  server:
    restart: always
    image: chris13524/privatepm-server:latest
    environment:
      - S3_ENDPOINT=$S3_ENDPOINT
      - S3_KEY_ID=$S3_KEY_ID
      - S3_KEY_SECRET=$S3_KEY_SECRET
      - S3_BUCKET=$S3_BUCKET
      - S3_PREFIX=$S3_PREFIX
    volumes:
      - ./server/database.sqlite3:/app/database.sqlite3

  appupdater-client:
    restart: always
    image: stixes/docker-hook:latest
    ports:
      - 8555:8555
    environment:
      CMD: sh /work/update-client.sh
      TOKEN: $UPDATE_TOKEN
    working_dir: /work
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - .:/work

  appupdater-server:
    restart: always
    image: stixes/docker-hook:latest
    ports:
      - 8556:8555
    environment:
      CMD: sh /work/update-server.sh
      TOKEN: $UPDATE_TOKEN
    working_dir: /work
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - .:/work

  exposer:
    restart: always
    image: valian/docker-nginx-auto-ssl
    environment:
      - ALLOWED_DOMAINS=$DOMAIN
      - SITES=$DOMAIN=client:80;api.$DOMAIN=server:80
    volumes:
      - ${DATA_DIR}/exposer/:/etc/resty-auto-ssl/
    ports:
      - "80:80"
      - "443:443"
